update nco invocation
E3SM-Project/e3sm_to_cmip pull request #93
Opened 2021-11-15 22:59 UTC by chengzhuzhang

Optimize nco invocation

2021-11-16 15:50 UTC, czender commented on e3sm_to_cmip/mpas.py
> +            'no_cell_measures', 'no_formula_terms', '--map={}'.format(mappingFileName), inFileName,
These two options need double-dashes preceding their names, `'no_cell_measures', 'no_formula_terms`. I do not see how a test of this patch could have succeeded.

2021-11-16 15:58 UTC, czender commented on scripts/cwl_workflows/atm-unified-eam/hrzremap_posin.cwl
>    - --regrid_options="--rnr=0.0"
I suggest changing this option from `--regrid_options="--rnr=0.0"` to `--preserve=local_mean`. It's clearer and it does the same thing in NCO 5.0.2 and later and I believe zppy is currently using NCO 5.0.3.

2021-11-16 15:59 UTC, czender commented on scripts/cwl_workflows/lnd-elm/ncremap_lnd.cwl
> +  - "-7"
Quotes on -7 not necessary

2021-11-16 16:00 UTC, czender requested changes
Please address in-line suggestions before merging

2022-10-25 21:15 UTC, chengzhuzhang commented
This is resolved with https://github.com/E3SM-Project/e3sm_to_cmip/pull/155

2022-10-25 21:15 UTC, closed without merging